// Generated by gencpp from file ys_ros_msgs/LanePlan.msg
// DO NOT EDIT!


#ifndef YS_ROS_MSGS_MESSAGE_LANEPLAN_H
#define YS_ROS_MSGS_MESSAGE_LANEPLAN_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ys_ros_msgs/PointXYA.h>
#include <ys_ros_msgs/PointXYA.h>

namespace ys_ros_msgs
{
template <class ContainerAllocator>
struct LanePlan_
{
  typedef LanePlan_<ContainerAllocator> Type;

  LanePlan_()
    : point_num(0)
    , points()
    , cur_pos()
    , speed(0)
    , gear(0)  {
    }
  LanePlan_(const ContainerAllocator& _alloc)
    : point_num(0)
    , points(_alloc)
    , cur_pos(_alloc)
    , speed(0)
    , gear(0)  {
  (void)_alloc;
    }



   typedef int32_t _point_num_type;
  _point_num_type point_num;

   typedef std::vector< ::ys_ros_msgs::PointXYA_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::ys_ros_msgs::PointXYA_<ContainerAllocator> >> _points_type;
  _points_type points;

   typedef  ::ys_ros_msgs::PointXYA_<ContainerAllocator>  _cur_pos_type;
  _cur_pos_type cur_pos;

   typedef int8_t _speed_type;
  _speed_type speed;

   typedef int8_t _gear_type;
  _gear_type gear;





  typedef boost::shared_ptr< ::ys_ros_msgs::LanePlan_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ys_ros_msgs::LanePlan_<ContainerAllocator> const> ConstPtr;

}; // struct LanePlan_

typedef ::ys_ros_msgs::LanePlan_<std::allocator<void> > LanePlan;

typedef boost::shared_ptr< ::ys_ros_msgs::LanePlan > LanePlanPtr;
typedef boost::shared_ptr< ::ys_ros_msgs::LanePlan const> LanePlanConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ys_ros_msgs::LanePlan_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ys_ros_msgs::LanePlan_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ys_ros_msgs::LanePlan_<ContainerAllocator1> & lhs, const ::ys_ros_msgs::LanePlan_<ContainerAllocator2> & rhs)
{
  return lhs.point_num == rhs.point_num &&
    lhs.points == rhs.points &&
    lhs.cur_pos == rhs.cur_pos &&
    lhs.speed == rhs.speed &&
    lhs.gear == rhs.gear;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ys_ros_msgs::LanePlan_<ContainerAllocator1> & lhs, const ::ys_ros_msgs::LanePlan_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ys_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ys_ros_msgs::LanePlan_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ys_ros_msgs::LanePlan_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ys_ros_msgs::LanePlan_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ys_ros_msgs::LanePlan_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ys_ros_msgs::LanePlan_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ys_ros_msgs::LanePlan_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ys_ros_msgs::LanePlan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "74956f693f7b4fb31d148cbde11780fb";
  }

  static const char* value(const ::ys_ros_msgs::LanePlan_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x74956f693f7b4fb3ULL;
  static const uint64_t static_value2 = 0x1d148cbde11780fbULL;
};

template<class ContainerAllocator>
struct DataType< ::ys_ros_msgs::LanePlan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ys_ros_msgs/LanePlan";
  }

  static const char* value(const ::ys_ros_msgs::LanePlan_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ys_ros_msgs::LanePlan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 point_num\n"
"PointXYA[] points\n"
"PointXYA cur_pos\n"
"int8 speed\n"
"int8 gear\n"
"================================================================================\n"
"MSG: ys_ros_msgs/PointXYA\n"
"Header header\n"
"float64 x\n"
"float64 y\n"
"float64 yaw  # degs\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::ys_ros_msgs::LanePlan_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ys_ros_msgs::LanePlan_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.point_num);
      stream.next(m.points);
      stream.next(m.cur_pos);
      stream.next(m.speed);
      stream.next(m.gear);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LanePlan_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ys_ros_msgs::LanePlan_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ys_ros_msgs::LanePlan_<ContainerAllocator>& v)
  {
    s << indent << "point_num: ";
    Printer<int32_t>::stream(s, indent + "  ", v.point_num);
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ys_ros_msgs::PointXYA_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
    s << indent << "cur_pos: ";
    s << std::endl;
    Printer< ::ys_ros_msgs::PointXYA_<ContainerAllocator> >::stream(s, indent + "  ", v.cur_pos);
    s << indent << "speed: ";
    Printer<int8_t>::stream(s, indent + "  ", v.speed);
    s << indent << "gear: ";
    Printer<int8_t>::stream(s, indent + "  ", v.gear);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YS_ROS_MSGS_MESSAGE_LANEPLAN_H
