// Generated by gencpp from file ys_ros_msgs/laneFinish.msg
// DO NOT EDIT!


#ifndef YS_ROS_MSGS_MESSAGE_LANEFINISH_H
#define YS_ROS_MSGS_MESSAGE_LANEFINISH_H

#include <ros/service_traits.h>


#include <ys_ros_msgs/laneFinishRequest.h>
#include <ys_ros_msgs/laneFinishResponse.h>


namespace ys_ros_msgs
{

struct laneFinish
{

typedef laneFinishRequest Request;
typedef laneFinishResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct laneFinish
} // namespace ys_ros_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ys_ros_msgs::laneFinish > {
  static const char* value()
  {
    return "173693392e9fa111283169251c339a9c";
  }

  static const char* value(const ::ys_ros_msgs::laneFinish&) { return value(); }
};

template<>
struct DataType< ::ys_ros_msgs::laneFinish > {
  static const char* value()
  {
    return "ys_ros_msgs/laneFinish";
  }

  static const char* value(const ::ys_ros_msgs::laneFinish&) { return value(); }
};


// service_traits::MD5Sum< ::ys_ros_msgs::laneFinishRequest> should match
// service_traits::MD5Sum< ::ys_ros_msgs::laneFinish >
template<>
struct MD5Sum< ::ys_ros_msgs::laneFinishRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ys_ros_msgs::laneFinish >::value();
  }
  static const char* value(const ::ys_ros_msgs::laneFinishRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ys_ros_msgs::laneFinishRequest> should match
// service_traits::DataType< ::ys_ros_msgs::laneFinish >
template<>
struct DataType< ::ys_ros_msgs::laneFinishRequest>
{
  static const char* value()
  {
    return DataType< ::ys_ros_msgs::laneFinish >::value();
  }
  static const char* value(const ::ys_ros_msgs::laneFinishRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ys_ros_msgs::laneFinishResponse> should match
// service_traits::MD5Sum< ::ys_ros_msgs::laneFinish >
template<>
struct MD5Sum< ::ys_ros_msgs::laneFinishResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ys_ros_msgs::laneFinish >::value();
  }
  static const char* value(const ::ys_ros_msgs::laneFinishResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ys_ros_msgs::laneFinishResponse> should match
// service_traits::DataType< ::ys_ros_msgs::laneFinish >
template<>
struct DataType< ::ys_ros_msgs::laneFinishResponse>
{
  static const char* value()
  {
    return DataType< ::ys_ros_msgs::laneFinish >::value();
  }
  static const char* value(const ::ys_ros_msgs::laneFinishResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // YS_ROS_MSGS_MESSAGE_LANEFINISH_H
