// Generated by gencpp from file ys_ros_msgs/LaneDetectionArray.msg
// DO NOT EDIT!


#ifndef YS_ROS_MSGS_MESSAGE_LANEDETECTIONARRAY_H
#define YS_ROS_MSGS_MESSAGE_LANEDETECTIONARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <ys_ros_msgs/LaneDetection.h>

namespace ys_ros_msgs
{
template <class ContainerAllocator>
struct LaneDetectionArray_
{
  typedef LaneDetectionArray_<ContainerAllocator> Type;

  LaneDetectionArray_()
    : header()
    , detections()  {
    }
  LaneDetectionArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , detections(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::ys_ros_msgs::LaneDetection_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::ys_ros_msgs::LaneDetection_<ContainerAllocator> >> _detections_type;
  _detections_type detections;





  typedef boost::shared_ptr< ::ys_ros_msgs::LaneDetectionArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ys_ros_msgs::LaneDetectionArray_<ContainerAllocator> const> ConstPtr;

}; // struct LaneDetectionArray_

typedef ::ys_ros_msgs::LaneDetectionArray_<std::allocator<void> > LaneDetectionArray;

typedef boost::shared_ptr< ::ys_ros_msgs::LaneDetectionArray > LaneDetectionArrayPtr;
typedef boost::shared_ptr< ::ys_ros_msgs::LaneDetectionArray const> LaneDetectionArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ys_ros_msgs::LaneDetectionArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ys_ros_msgs::LaneDetectionArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ys_ros_msgs::LaneDetectionArray_<ContainerAllocator1> & lhs, const ::ys_ros_msgs::LaneDetectionArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.detections == rhs.detections;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ys_ros_msgs::LaneDetectionArray_<ContainerAllocator1> & lhs, const ::ys_ros_msgs::LaneDetectionArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ys_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ys_ros_msgs::LaneDetectionArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ys_ros_msgs::LaneDetectionArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ys_ros_msgs::LaneDetectionArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ys_ros_msgs::LaneDetectionArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ys_ros_msgs::LaneDetectionArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ys_ros_msgs::LaneDetectionArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ys_ros_msgs::LaneDetectionArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c93a62e7777b4d80f9bf607c90c25a61";
  }

  static const char* value(const ::ys_ros_msgs::LaneDetectionArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc93a62e7777b4d80ULL;
  static const uint64_t static_value2 = 0xf9bf607c90c25a61ULL;
};

template<class ContainerAllocator>
struct DataType< ::ys_ros_msgs::LaneDetectionArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ys_ros_msgs/LaneDetectionArray";
  }

  static const char* value(const ::ys_ros_msgs::LaneDetectionArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ys_ros_msgs::LaneDetectionArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"LaneDetection[] detections\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: ys_ros_msgs/LaneDetection\n"
"int8 id     # lane number\n"
"\n"
"geometry_msgs/Point32[] points   # lane point list\n"
"================================================================================\n"
"MSG: geometry_msgs/Point32\n"
"# This contains the position of a point in free space(with 32 bits of precision).\n"
"# It is recommeded to use Point wherever possible instead of Point32.  \n"
"# \n"
"# This recommendation is to promote interoperability.  \n"
"#\n"
"# This message is designed to take up less space when sending\n"
"# lots of points at once, as in the case of a PointCloud.  \n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::ys_ros_msgs::LaneDetectionArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ys_ros_msgs::LaneDetectionArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.detections);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LaneDetectionArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ys_ros_msgs::LaneDetectionArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ys_ros_msgs::LaneDetectionArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "detections[]" << std::endl;
    for (size_t i = 0; i < v.detections.size(); ++i)
    {
      s << indent << "  detections[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ys_ros_msgs::LaneDetection_<ContainerAllocator> >::stream(s, indent + "    ", v.detections[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // YS_ROS_MSGS_MESSAGE_LANEDETECTIONARRAY_H
