// Generated by gencpp from file ys_ros_msgs/Location.msg
// DO NOT EDIT!


#ifndef YS_ROS_MSGS_MESSAGE_LOCATION_H
#define YS_ROS_MSGS_MESSAGE_LOCATION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ys_ros_msgs
{
template <class ContainerAllocator>
struct Location_
{
  typedef Location_<ContainerAllocator> Type;

  Location_()
    : header()
    , ins_time()
    , gau_pos()
    , wgs84_pos()
    , orientation()
    , speed()
    , accelerate()
    , gyro()
    , ins_std_error()
    , ins_data_info()
    , INS_status()  {
      ins_time.assign(0);

      gau_pos.assign(0.0);

      wgs84_pos.assign(0.0);

      orientation.assign(0.0);

      speed.assign(0.0);

      accelerate.assign(0.0);

      gyro.assign(0.0);

      ins_std_error.assign(0.0);

      ins_data_info.assign(0);
  }
  Location_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ins_time()
    , gau_pos()
    , wgs84_pos()
    , orientation()
    , speed()
    , accelerate()
    , gyro()
    , ins_std_error()
    , ins_data_info()
    , INS_status(_alloc)  {
  (void)_alloc;
      ins_time.assign(0);

      gau_pos.assign(0.0);

      wgs84_pos.assign(0.0);

      orientation.assign(0.0);

      speed.assign(0.0);

      accelerate.assign(0.0);

      gyro.assign(0.0);

      ins_std_error.assign(0.0);

      ins_data_info.assign(0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array<int32_t, 2>  _ins_time_type;
  _ins_time_type ins_time;

   typedef boost::array<double, 2>  _gau_pos_type;
  _gau_pos_type gau_pos;

   typedef boost::array<double, 3>  _wgs84_pos_type;
  _wgs84_pos_type wgs84_pos;

   typedef boost::array<float, 3>  _orientation_type;
  _orientation_type orientation;

   typedef boost::array<float, 3>  _speed_type;
  _speed_type speed;

   typedef boost::array<float, 3>  _accelerate_type;
  _accelerate_type accelerate;

   typedef boost::array<float, 3>  _gyro_type;
  _gyro_type gyro;

   typedef boost::array<float, 4>  _ins_std_error_type;
  _ins_std_error_type ins_std_error;

   typedef boost::array<int32_t, 3>  _ins_data_info_type;
  _ins_data_info_type ins_data_info;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _INS_status_type;
  _INS_status_type INS_status;





  typedef boost::shared_ptr< ::ys_ros_msgs::Location_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ys_ros_msgs::Location_<ContainerAllocator> const> ConstPtr;

}; // struct Location_

typedef ::ys_ros_msgs::Location_<std::allocator<void> > Location;

typedef boost::shared_ptr< ::ys_ros_msgs::Location > LocationPtr;
typedef boost::shared_ptr< ::ys_ros_msgs::Location const> LocationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ys_ros_msgs::Location_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ys_ros_msgs::Location_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ys_ros_msgs::Location_<ContainerAllocator1> & lhs, const ::ys_ros_msgs::Location_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.ins_time == rhs.ins_time &&
    lhs.gau_pos == rhs.gau_pos &&
    lhs.wgs84_pos == rhs.wgs84_pos &&
    lhs.orientation == rhs.orientation &&
    lhs.speed == rhs.speed &&
    lhs.accelerate == rhs.accelerate &&
    lhs.gyro == rhs.gyro &&
    lhs.ins_std_error == rhs.ins_std_error &&
    lhs.ins_data_info == rhs.ins_data_info &&
    lhs.INS_status == rhs.INS_status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ys_ros_msgs::Location_<ContainerAllocator1> & lhs, const ::ys_ros_msgs::Location_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ys_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ys_ros_msgs::Location_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ys_ros_msgs::Location_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ys_ros_msgs::Location_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ys_ros_msgs::Location_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ys_ros_msgs::Location_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ys_ros_msgs::Location_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ys_ros_msgs::Location_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2f2d9b0d226b62d4d28d5ba0a19bf067";
  }

  static const char* value(const ::ys_ros_msgs::Location_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2f2d9b0d226b62d4ULL;
  static const uint64_t static_value2 = 0xd28d5ba0a19bf067ULL;
};

template<class ContainerAllocator>
struct DataType< ::ys_ros_msgs::Location_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ys_ros_msgs/Location";
  }

  static const char* value(const ::ys_ros_msgs::Location_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ys_ros_msgs::Location_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header	   header # ROS time\n"
"int32[2]   ins_time # GPS weeks, GPS million seconds\n"
"float64[2] gau_pos # Guass frame(m)\n"
"float64[3] wgs84_pos # WGS84\n"
"float32[3] orientation # Guass frame(deg), X-front, Y-right, Z-down\n"
"float32[3] speed # Guass frame(m/s)\n"
"float32[3] accelerate # IMU frame(g)\n"
"float32[3] gyro # IMU frame(deg/s)\n"
"float32[4] ins_std_error # std_lat, std_lon, std_height, std_heading\n"
"int32[3]   ins_data_info # ins_num_satellite, gps_delay , wheel_speed\n"
"string     INS_status # 0_NONE_,  16_SINGLE_, 17_PSRDIFF_ , 34_NARROW_FLOAT_, 50_NARROW_INT_\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::ys_ros_msgs::Location_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ys_ros_msgs::Location_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ins_time);
      stream.next(m.gau_pos);
      stream.next(m.wgs84_pos);
      stream.next(m.orientation);
      stream.next(m.speed);
      stream.next(m.accelerate);
      stream.next(m.gyro);
      stream.next(m.ins_std_error);
      stream.next(m.ins_data_info);
      stream.next(m.INS_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Location_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ys_ros_msgs::Location_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ys_ros_msgs::Location_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ins_time[]" << std::endl;
    for (size_t i = 0; i < v.ins_time.size(); ++i)
    {
      s << indent << "  ins_time[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.ins_time[i]);
    }
    s << indent << "gau_pos[]" << std::endl;
    for (size_t i = 0; i < v.gau_pos.size(); ++i)
    {
      s << indent << "  gau_pos[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.gau_pos[i]);
    }
    s << indent << "wgs84_pos[]" << std::endl;
    for (size_t i = 0; i < v.wgs84_pos.size(); ++i)
    {
      s << indent << "  wgs84_pos[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.wgs84_pos[i]);
    }
    s << indent << "orientation[]" << std::endl;
    for (size_t i = 0; i < v.orientation.size(); ++i)
    {
      s << indent << "  orientation[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.orientation[i]);
    }
    s << indent << "speed[]" << std::endl;
    for (size_t i = 0; i < v.speed.size(); ++i)
    {
      s << indent << "  speed[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.speed[i]);
    }
    s << indent << "accelerate[]" << std::endl;
    for (size_t i = 0; i < v.accelerate.size(); ++i)
    {
      s << indent << "  accelerate[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.accelerate[i]);
    }
    s << indent << "gyro[]" << std::endl;
    for (size_t i = 0; i < v.gyro.size(); ++i)
    {
      s << indent << "  gyro[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.gyro[i]);
    }
    s << indent << "ins_std_error[]" << std::endl;
    for (size_t i = 0; i < v.ins_std_error.size(); ++i)
    {
      s << indent << "  ins_std_error[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.ins_std_error[i]);
    }
    s << indent << "ins_data_info[]" << std::endl;
    for (size_t i = 0; i < v.ins_data_info.size(); ++i)
    {
      s << indent << "  ins_data_info[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.ins_data_info[i]);
    }
    s << indent << "INS_status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.INS_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YS_ROS_MSGS_MESSAGE_LOCATION_H
