// Generated by gencpp from file ys_ros_msgs/VehicleFeed.msg
// DO NOT EDIT!


#ifndef YS_ROS_MSGS_MESSAGE_VEHICLEFEED_H
#define YS_ROS_MSGS_MESSAGE_VEHICLEFEED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ys_ros_msgs
{
template <class ContainerAllocator>
struct VehicleFeed_
{
  typedef VehicleFeed_<ContainerAllocator> Type;

  VehicleFeed_()
    : header()
    , timestamp()
    , LFspd(0.0)
    , LBspd(0.0)
    , RFspd(0.0)
    , RBspd(0.0)
    , gear(0)
    , speed(0.0)
    , steerAng(0.0)  {
    }
  VehicleFeed_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , timestamp()
    , LFspd(0.0)
    , LBspd(0.0)
    , RFspd(0.0)
    , RBspd(0.0)
    , gear(0)
    , speed(0.0)
    , steerAng(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef ros::Time _timestamp_type;
  _timestamp_type timestamp;

   typedef double _LFspd_type;
  _LFspd_type LFspd;

   typedef double _LBspd_type;
  _LBspd_type LBspd;

   typedef double _RFspd_type;
  _RFspd_type RFspd;

   typedef double _RBspd_type;
  _RBspd_type RBspd;

   typedef int8_t _gear_type;
  _gear_type gear;

   typedef double _speed_type;
  _speed_type speed;

   typedef double _steerAng_type;
  _steerAng_type steerAng;





  typedef boost::shared_ptr< ::ys_ros_msgs::VehicleFeed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ys_ros_msgs::VehicleFeed_<ContainerAllocator> const> ConstPtr;

}; // struct VehicleFeed_

typedef ::ys_ros_msgs::VehicleFeed_<std::allocator<void> > VehicleFeed;

typedef boost::shared_ptr< ::ys_ros_msgs::VehicleFeed > VehicleFeedPtr;
typedef boost::shared_ptr< ::ys_ros_msgs::VehicleFeed const> VehicleFeedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ys_ros_msgs::VehicleFeed_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ys_ros_msgs::VehicleFeed_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ys_ros_msgs::VehicleFeed_<ContainerAllocator1> & lhs, const ::ys_ros_msgs::VehicleFeed_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.timestamp == rhs.timestamp &&
    lhs.LFspd == rhs.LFspd &&
    lhs.LBspd == rhs.LBspd &&
    lhs.RFspd == rhs.RFspd &&
    lhs.RBspd == rhs.RBspd &&
    lhs.gear == rhs.gear &&
    lhs.speed == rhs.speed &&
    lhs.steerAng == rhs.steerAng;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ys_ros_msgs::VehicleFeed_<ContainerAllocator1> & lhs, const ::ys_ros_msgs::VehicleFeed_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ys_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ys_ros_msgs::VehicleFeed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ys_ros_msgs::VehicleFeed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ys_ros_msgs::VehicleFeed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ys_ros_msgs::VehicleFeed_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ys_ros_msgs::VehicleFeed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ys_ros_msgs::VehicleFeed_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ys_ros_msgs::VehicleFeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "138084c58c4fbccd8851afdacaa5730e";
  }

  static const char* value(const ::ys_ros_msgs::VehicleFeed_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x138084c58c4fbccdULL;
  static const uint64_t static_value2 = 0x8851afdacaa5730eULL;
};

template<class ContainerAllocator>
struct DataType< ::ys_ros_msgs::VehicleFeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ys_ros_msgs/VehicleFeed";
  }

  static const char* value(const ::ys_ros_msgs::VehicleFeed_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ys_ros_msgs::VehicleFeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"# feed of wheel speed and gear for INS\n"
"time timestamp\n"
"float64 LFspd  #left front, km/h\n"
"float64 LBspd  #left behind km/h\n"
"float64 RFspd  #right front km/h\n"
"float64 RBspd  #right behind km/h\n"
"int8 gear   # P R N D 1 2 3 4\n"
"float64 speed #车速，km/h\n"
"float64 steerAng # 方向盘转角，左正右负,deg\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::ys_ros_msgs::VehicleFeed_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ys_ros_msgs::VehicleFeed_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.timestamp);
      stream.next(m.LFspd);
      stream.next(m.LBspd);
      stream.next(m.RFspd);
      stream.next(m.RBspd);
      stream.next(m.gear);
      stream.next(m.speed);
      stream.next(m.steerAng);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VehicleFeed_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ys_ros_msgs::VehicleFeed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ys_ros_msgs::VehicleFeed_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "timestamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.timestamp);
    s << indent << "LFspd: ";
    Printer<double>::stream(s, indent + "  ", v.LFspd);
    s << indent << "LBspd: ";
    Printer<double>::stream(s, indent + "  ", v.LBspd);
    s << indent << "RFspd: ";
    Printer<double>::stream(s, indent + "  ", v.RFspd);
    s << indent << "RBspd: ";
    Printer<double>::stream(s, indent + "  ", v.RBspd);
    s << indent << "gear: ";
    Printer<int8_t>::stream(s, indent + "  ", v.gear);
    s << indent << "speed: ";
    Printer<double>::stream(s, indent + "  ", v.speed);
    s << indent << "steerAng: ";
    Printer<double>::stream(s, indent + "  ", v.steerAng);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YS_ROS_MSGS_MESSAGE_VEHICLEFEED_H
