// Generated by gencpp from file ys_ros_msgs/VehicleCMD.msg
// DO NOT EDIT!


#ifndef YS_ROS_MSGS_MESSAGE_VEHICLECMD_H
#define YS_ROS_MSGS_MESSAGE_VEHICLECMD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ys_ros_msgs
{
template <class ContainerAllocator>
struct VehicleCMD_
{
  typedef VehicleCMD_<ContainerAllocator> Type;

  VehicleCMD_()
    : header()
    , timestamp()
    , steerAngle(0.0)
    , vehicleSpeed(0.0)
    , acceleration(0.0)
    , steerAngle_speed(0)
    , gear(0)
    , controlStatus(0)
    , enable_acceleration(0)  {
    }
  VehicleCMD_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , timestamp()
    , steerAngle(0.0)
    , vehicleSpeed(0.0)
    , acceleration(0.0)
    , steerAngle_speed(0)
    , gear(0)
    , controlStatus(0)
    , enable_acceleration(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef ros::Time _timestamp_type;
  _timestamp_type timestamp;

   typedef double _steerAngle_type;
  _steerAngle_type steerAngle;

   typedef double _vehicleSpeed_type;
  _vehicleSpeed_type vehicleSpeed;

   typedef double _acceleration_type;
  _acceleration_type acceleration;

   typedef uint16_t _steerAngle_speed_type;
  _steerAngle_speed_type steerAngle_speed;

   typedef int8_t _gear_type;
  _gear_type gear;

   typedef int8_t _controlStatus_type;
  _controlStatus_type controlStatus;

   typedef uint8_t _enable_acceleration_type;
  _enable_acceleration_type enable_acceleration;





  typedef boost::shared_ptr< ::ys_ros_msgs::VehicleCMD_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ys_ros_msgs::VehicleCMD_<ContainerAllocator> const> ConstPtr;

}; // struct VehicleCMD_

typedef ::ys_ros_msgs::VehicleCMD_<std::allocator<void> > VehicleCMD;

typedef boost::shared_ptr< ::ys_ros_msgs::VehicleCMD > VehicleCMDPtr;
typedef boost::shared_ptr< ::ys_ros_msgs::VehicleCMD const> VehicleCMDConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ys_ros_msgs::VehicleCMD_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ys_ros_msgs::VehicleCMD_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ys_ros_msgs::VehicleCMD_<ContainerAllocator1> & lhs, const ::ys_ros_msgs::VehicleCMD_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.timestamp == rhs.timestamp &&
    lhs.steerAngle == rhs.steerAngle &&
    lhs.vehicleSpeed == rhs.vehicleSpeed &&
    lhs.acceleration == rhs.acceleration &&
    lhs.steerAngle_speed == rhs.steerAngle_speed &&
    lhs.gear == rhs.gear &&
    lhs.controlStatus == rhs.controlStatus &&
    lhs.enable_acceleration == rhs.enable_acceleration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ys_ros_msgs::VehicleCMD_<ContainerAllocator1> & lhs, const ::ys_ros_msgs::VehicleCMD_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ys_ros_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ys_ros_msgs::VehicleCMD_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ys_ros_msgs::VehicleCMD_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ys_ros_msgs::VehicleCMD_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ys_ros_msgs::VehicleCMD_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ys_ros_msgs::VehicleCMD_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ys_ros_msgs::VehicleCMD_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ys_ros_msgs::VehicleCMD_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9029582b3d2c81df872873daf779f6b8";
  }

  static const char* value(const ::ys_ros_msgs::VehicleCMD_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9029582b3d2c81dfULL;
  static const uint64_t static_value2 = 0x872873daf779f6b8ULL;
};

template<class ContainerAllocator>
struct DataType< ::ys_ros_msgs::VehicleCMD_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ys_ros_msgs/VehicleCMD";
  }

  static const char* value(const ::ys_ros_msgs::VehicleCMD_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ys_ros_msgs::VehicleCMD_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"time timestamp\n"
"float64 steerAngle\n"
"float64 vehicleSpeed\n"
"float64 acceleration\n"
"uint16 steerAngle_speed\n"
"int8 gear\n"
"int8 controlStatus    #force_stop:0, stop：1, forward：2, back：3, idle：4\n"
"\n"
"uint8 enable_acceleration #是否使用CMD的加速度。0不用， 1用\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::ys_ros_msgs::VehicleCMD_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ys_ros_msgs::VehicleCMD_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.timestamp);
      stream.next(m.steerAngle);
      stream.next(m.vehicleSpeed);
      stream.next(m.acceleration);
      stream.next(m.steerAngle_speed);
      stream.next(m.gear);
      stream.next(m.controlStatus);
      stream.next(m.enable_acceleration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VehicleCMD_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ys_ros_msgs::VehicleCMD_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ys_ros_msgs::VehicleCMD_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "timestamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.timestamp);
    s << indent << "steerAngle: ";
    Printer<double>::stream(s, indent + "  ", v.steerAngle);
    s << indent << "vehicleSpeed: ";
    Printer<double>::stream(s, indent + "  ", v.vehicleSpeed);
    s << indent << "acceleration: ";
    Printer<double>::stream(s, indent + "  ", v.acceleration);
    s << indent << "steerAngle_speed: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.steerAngle_speed);
    s << indent << "gear: ";
    Printer<int8_t>::stream(s, indent + "  ", v.gear);
    s << indent << "controlStatus: ";
    Printer<int8_t>::stream(s, indent + "  ", v.controlStatus);
    s << indent << "enable_acceleration: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enable_acceleration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YS_ROS_MSGS_MESSAGE_VEHICLECMD_H
