# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ys_ros_msgs/VehicleFeed.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy
import std_msgs.msg

class VehicleFeed(genpy.Message):
  _md5sum = "138084c58c4fbccd8851afdacaa5730e"
  _type = "ys_ros_msgs/VehicleFeed"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header
# feed of wheel speed and gear for INS
time timestamp
float64 LFspd  #left front, km/h
float64 LBspd  #left behind km/h
float64 RFspd  #right front km/h
float64 RBspd  #right behind km/h
int8 gear   # P R N D 1 2 3 4
float64 speed #车速，km/h
float64 steerAng # 方向盘转角，左正右负,deg

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','timestamp','LFspd','LBspd','RFspd','RBspd','gear','speed','steerAng']
  _slot_types = ['std_msgs/Header','time','float64','float64','float64','float64','int8','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,timestamp,LFspd,LBspd,RFspd,RBspd,gear,speed,steerAng

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(VehicleFeed, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.timestamp is None:
        self.timestamp = genpy.Time()
      if self.LFspd is None:
        self.LFspd = 0.
      if self.LBspd is None:
        self.LBspd = 0.
      if self.RFspd is None:
        self.RFspd = 0.
      if self.RBspd is None:
        self.RBspd = 0.
      if self.gear is None:
        self.gear = 0
      if self.speed is None:
        self.speed = 0.
      if self.steerAng is None:
        self.steerAng = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.timestamp = genpy.Time()
      self.LFspd = 0.
      self.LBspd = 0.
      self.RFspd = 0.
      self.RBspd = 0.
      self.gear = 0
      self.speed = 0.
      self.steerAng = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I4db2d().pack(_x.timestamp.secs, _x.timestamp.nsecs, _x.LFspd, _x.LBspd, _x.RFspd, _x.RBspd, _x.gear, _x.speed, _x.steerAng))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.timestamp is None:
        self.timestamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 57
      (_x.timestamp.secs, _x.timestamp.nsecs, _x.LFspd, _x.LBspd, _x.RFspd, _x.RBspd, _x.gear, _x.speed, _x.steerAng,) = _get_struct_2I4db2d().unpack(str[start:end])
      self.timestamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I4db2d().pack(_x.timestamp.secs, _x.timestamp.nsecs, _x.LFspd, _x.LBspd, _x.RFspd, _x.RBspd, _x.gear, _x.speed, _x.steerAng))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.timestamp is None:
        self.timestamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 57
      (_x.timestamp.secs, _x.timestamp.nsecs, _x.LFspd, _x.LBspd, _x.RFspd, _x.RBspd, _x.gear, _x.speed, _x.steerAng,) = _get_struct_2I4db2d().unpack(str[start:end])
      self.timestamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I4db2d = None
def _get_struct_2I4db2d():
    global _struct_2I4db2d
    if _struct_2I4db2d is None:
        _struct_2I4db2d = struct.Struct("<2I4db2d")
    return _struct_2I4db2d
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
